name: Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      - name: List up fileds
        run: ls -al
      - name: Checkout repo source code
        uses: actions/checkout@v3
      - name: Confirm checkout repo
        run: ls -al
