name: Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
      
      - name: Zipping files
        run: zip function.zip index.js node_modules/**/* package.json package-lock.json src/*
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
          --function-name createNotionPlannerPage \
          --zip-file fileb://function.zip

